apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
---
apiVersion: v1
kind: Secret
metadata:
  name: foo
  annotations:
    kubernetes.io/service-account.name: foo
type: kubernetes.io/service-account-token
